name: Tests

on:
  push:
    paths: 
      - 'clairvoyance/**'
      - 'tests/**'
      - '.github/workflows/*'
    branches:
      - main
      - master
  pull_request:
    paths:
      - 'clairvoyance/**'
      - 'tests/**'
      - '.github/workflows/*'
    branches:
      - main
      - master

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m unittest tests/*_test.py

  system-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Clone SWAPI and install dependencies
      run: |
        cd /tmp
        git clone https://github.com/graphql/swapi-graphql.git
        cd swapi-graphql
        git checkout 8e9329077630000d66b53c031b3d3e6cc4f9052a
        npm install
    - name: Test with pytest
      run: |
        python -m unittest tests/system.py
