name: Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
    branches:
      - main
      - master

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m unittest tests/*_test.py

  system-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install deps and run server
      run: |
        cd tests/apollo-server
        npm install
        node src/index.js &
    - name: Wait for server
      run: |
        echo "SERVER=http://localhost:4000" > $GITHUB_ENV

        for i in {0..9}; do
          echo "Sleep for 1 second ..."
          sleep 1
          if curl -s -o /dev/null "$SERVER"; then
            echo "$SERVER returned HTTP response!"
            break
          fi
        done
    - name: Test with pytest
      run: |
        python -m unittest tests/system.py
